### ISSUE TITLE
CZForecastRequestType doesn't return data

### ISSUE THREAD

**Issue by authiatr** [CZWeatherKit/CZWeatherKit#13]
When I'm trying to get the forecast, the return value is empty. 
This is the code: 

CZWeatherRequest *request = [CZWeatherRequest requestWithType:CZForecastRequestType];
    request.location          = [CZWeatherLocation locationWithCity:<city> country:<country>];
    request.service           = [CZWundergroundService serviceWithKey:<APIKey>];
    request.detailLevel       = CZWeatherRequestFullDetail;
    [request performRequestWithHandler:^(id data, NSError *error) {
        if (data) {
            forecasts = (NSArray *)data;
            NSLog(@"%@", data);
        }
        else
            NSLog(@"%@", error);
    }];

**Comment by comyarzaheri** [comment]
So I tried this on my end and I'm not finding any issues. Have you verified that everything else is configured correctly (e.g. API key, location, etc)?

**Comment by comyarzaheri** [comment]
I'll go ahead and close this issue. If you continue seeing the problem feel free to reopen it.
